export enum USER_ROLE {
  USER = 'user',
  SUPERADMIN = 'superadmin',
  ADMIN = 'admin',
  VENDEUR = 'vendeur',
  CAISSIER = 'caissier',
  ACP = 'acp',
  CONTROLEUR = 'controleur',
  RECOUVREUR = 'recouvreur',
  REPREUNEUR = 'repreuneur',
  CHEF_DIV_RESTAURANT = 'chef_div_restaurant',
  CHEF_CODIFICATION = 'chef_codification',
  CHEF_SPORT = 'chef_sport',
  SUPERVISEUR = 'superviseur',
}