/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUnauthorizedRouteImport } from './routes/admin/unauthorized'
import { Route as AdminTicketsIndexRouteImport } from './routes/admin/tickets/index'
import { Route as AdminSessionsIndexRouteImport } from './routes/admin/sessions/index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as AdminRestaurationsIndexRouteImport } from './routes/admin/restaurations/index'
import { Route as AdminRepreuneursIndexRouteImport } from './routes/admin/repreuneurs/index'
import { Route as AdminRecouvrementIndexRouteImport } from './routes/admin/recouvrement/index'
import { Route as AdminRechargeIndexRouteImport } from './routes/admin/recharge/index'
import { Route as AdminEtudiantsIndexRouteImport } from './routes/admin/etudiants/index'
import { Route as AdminDecadesIndexRouteImport } from './routes/admin/decades/index'
import { Route as AdminControleursIndexRouteImport } from './routes/admin/controleurs/index'
import { Route as AdminComptesIndexRouteImport } from './routes/admin/comptes/index'
import { Route as AdminCaissePrincipaleIndexRouteImport } from './routes/admin/caisse-principale/index'
import { Route as AdminAgentComptableIndexRouteImport } from './routes/admin/agent-comptable/index'
import { Route as AdminServicesServiceIdRouteImport } from './routes/admin/services/$serviceId'
import { Route as AdminRestaurationsRestaurantIdRouteImport } from './routes/admin/restaurations/$restaurantId'
import { Route as AdminRepreuneursServiceIdRouteImport } from './routes/admin/repreuneurs/$serviceId'
import { Route as AdminEtudiantsEtudiantIdRouteImport } from './routes/admin/etudiants/$etudiantId'
import { Route as AdminComptesCompteIdRouteImport } from './routes/admin/comptes/$compteId'
import { Route as AdminRechargeMobileIndexRouteImport } from './routes/admin/recharge/mobile/index'
import { Route as AdminControleursServiceIdIndexRouteImport } from './routes/admin/controleurs/$serviceId/index'
import { Route as AdminControleursServiceIdTicketTicketIdIndexRouteImport } from './routes/admin/controleurs/$serviceId/ticket/$ticketId/index'
import { Route as AdminControleursServiceIdTicketTicketIdMobileIndexRouteImport } from './routes/admin/controleurs/$serviceId/ticket/$ticketId/mobile/index'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUnauthorizedRoute = AdminUnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsIndexRoute = AdminTicketsIndexRouteImport.update({
  id: '/tickets/',
  path: '/tickets/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsIndexRoute = AdminSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurationsIndexRoute = AdminRestaurationsIndexRouteImport.update({
  id: '/restaurations/',
  path: '/restaurations/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRepreuneursIndexRoute = AdminRepreuneursIndexRouteImport.update({
  id: '/repreuneurs/',
  path: '/repreuneurs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecouvrementIndexRoute = AdminRecouvrementIndexRouteImport.update({
  id: '/recouvrement/',
  path: '/recouvrement/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargeIndexRoute = AdminRechargeIndexRouteImport.update({
  id: '/recharge/',
  path: '/recharge/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEtudiantsIndexRoute = AdminEtudiantsIndexRouteImport.update({
  id: '/etudiants/',
  path: '/etudiants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDecadesIndexRoute = AdminDecadesIndexRouteImport.update({
  id: '/decades/',
  path: '/decades/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminControleursIndexRoute = AdminControleursIndexRouteImport.update({
  id: '/controleurs/',
  path: '/controleurs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComptesIndexRoute = AdminComptesIndexRouteImport.update({
  id: '/comptes/',
  path: '/comptes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaissePrincipaleIndexRoute =
  AdminCaissePrincipaleIndexRouteImport.update({
    id: '/caisse-principale/',
    path: '/caisse-principale/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminAgentComptableIndexRoute =
  AdminAgentComptableIndexRouteImport.update({
    id: '/agent-comptable/',
    path: '/agent-comptable/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminServicesServiceIdRoute = AdminServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRestaurationsRestaurantIdRoute =
  AdminRestaurationsRestaurantIdRouteImport.update({
    id: '/restaurations/$restaurantId',
    path: '/restaurations/$restaurantId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminRepreuneursServiceIdRoute =
  AdminRepreuneursServiceIdRouteImport.update({
    id: '/repreuneurs/$serviceId',
    path: '/repreuneurs/$serviceId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEtudiantsEtudiantIdRoute =
  AdminEtudiantsEtudiantIdRouteImport.update({
    id: '/etudiants/$etudiantId',
    path: '/etudiants/$etudiantId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminComptesCompteIdRoute = AdminComptesCompteIdRouteImport.update({
  id: '/comptes/$compteId',
  path: '/comptes/$compteId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRechargeMobileIndexRoute =
  AdminRechargeMobileIndexRouteImport.update({
    id: '/recharge/mobile/',
    path: '/recharge/mobile/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminControleursServiceIdIndexRoute =
  AdminControleursServiceIdIndexRouteImport.update({
    id: '/controleurs/$serviceId/',
    path: '/controleurs/$serviceId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminControleursServiceIdTicketTicketIdIndexRoute =
  AdminControleursServiceIdTicketTicketIdIndexRouteImport.update({
    id: '/controleurs/$serviceId/ticket/$ticketId/',
    path: '/controleurs/$serviceId/ticket/$ticketId/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminControleursServiceIdTicketTicketIdMobileIndexRoute =
  AdminControleursServiceIdTicketTicketIdMobileIndexRouteImport.update({
    id: '/controleurs/$serviceId/ticket/$ticketId/mobile/',
    path: '/controleurs/$serviceId/ticket/$ticketId/mobile/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/comptes/$compteId': typeof AdminComptesCompteIdRoute
  '/admin/etudiants/$etudiantId': typeof AdminEtudiantsEtudiantIdRoute
  '/admin/repreuneurs/$serviceId': typeof AdminRepreuneursServiceIdRoute
  '/admin/restaurations/$restaurantId': typeof AdminRestaurationsRestaurantIdRoute
  '/admin/services/$serviceId': typeof AdminServicesServiceIdRoute
  '/admin/agent-comptable/': typeof AdminAgentComptableIndexRoute
  '/admin/caisse-principale/': typeof AdminCaissePrincipaleIndexRoute
  '/admin/comptes/': typeof AdminComptesIndexRoute
  '/admin/controleurs/': typeof AdminControleursIndexRoute
  '/admin/decades/': typeof AdminDecadesIndexRoute
  '/admin/etudiants/': typeof AdminEtudiantsIndexRoute
  '/admin/recharge/': typeof AdminRechargeIndexRoute
  '/admin/recouvrement/': typeof AdminRecouvrementIndexRoute
  '/admin/repreuneurs/': typeof AdminRepreuneursIndexRoute
  '/admin/restaurations/': typeof AdminRestaurationsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/admin/controleurs/$serviceId/': typeof AdminControleursServiceIdIndexRoute
  '/admin/recharge/mobile/': typeof AdminRechargeMobileIndexRoute
  '/admin/controleurs/$serviceId/ticket/$ticketId/': typeof AdminControleursServiceIdTicketTicketIdIndexRoute
  '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/': typeof AdminControleursServiceIdTicketTicketIdMobileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin': typeof AdminIndexRoute
  '/admin/comptes/$compteId': typeof AdminComptesCompteIdRoute
  '/admin/etudiants/$etudiantId': typeof AdminEtudiantsEtudiantIdRoute
  '/admin/repreuneurs/$serviceId': typeof AdminRepreuneursServiceIdRoute
  '/admin/restaurations/$restaurantId': typeof AdminRestaurationsRestaurantIdRoute
  '/admin/services/$serviceId': typeof AdminServicesServiceIdRoute
  '/admin/agent-comptable': typeof AdminAgentComptableIndexRoute
  '/admin/caisse-principale': typeof AdminCaissePrincipaleIndexRoute
  '/admin/comptes': typeof AdminComptesIndexRoute
  '/admin/controleurs': typeof AdminControleursIndexRoute
  '/admin/decades': typeof AdminDecadesIndexRoute
  '/admin/etudiants': typeof AdminEtudiantsIndexRoute
  '/admin/recharge': typeof AdminRechargeIndexRoute
  '/admin/recouvrement': typeof AdminRecouvrementIndexRoute
  '/admin/repreuneurs': typeof AdminRepreuneursIndexRoute
  '/admin/restaurations': typeof AdminRestaurationsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/sessions': typeof AdminSessionsIndexRoute
  '/admin/tickets': typeof AdminTicketsIndexRoute
  '/admin/controleurs/$serviceId': typeof AdminControleursServiceIdIndexRoute
  '/admin/recharge/mobile': typeof AdminRechargeMobileIndexRoute
  '/admin/controleurs/$serviceId/ticket/$ticketId': typeof AdminControleursServiceIdTicketTicketIdIndexRoute
  '/admin/controleurs/$serviceId/ticket/$ticketId/mobile': typeof AdminControleursServiceIdTicketTicketIdMobileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/unauthorized': typeof AdminUnauthorizedRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/comptes/$compteId': typeof AdminComptesCompteIdRoute
  '/admin/etudiants/$etudiantId': typeof AdminEtudiantsEtudiantIdRoute
  '/admin/repreuneurs/$serviceId': typeof AdminRepreuneursServiceIdRoute
  '/admin/restaurations/$restaurantId': typeof AdminRestaurationsRestaurantIdRoute
  '/admin/services/$serviceId': typeof AdminServicesServiceIdRoute
  '/admin/agent-comptable/': typeof AdminAgentComptableIndexRoute
  '/admin/caisse-principale/': typeof AdminCaissePrincipaleIndexRoute
  '/admin/comptes/': typeof AdminComptesIndexRoute
  '/admin/controleurs/': typeof AdminControleursIndexRoute
  '/admin/decades/': typeof AdminDecadesIndexRoute
  '/admin/etudiants/': typeof AdminEtudiantsIndexRoute
  '/admin/recharge/': typeof AdminRechargeIndexRoute
  '/admin/recouvrement/': typeof AdminRecouvrementIndexRoute
  '/admin/repreuneurs/': typeof AdminRepreuneursIndexRoute
  '/admin/restaurations/': typeof AdminRestaurationsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/sessions/': typeof AdminSessionsIndexRoute
  '/admin/tickets/': typeof AdminTicketsIndexRoute
  '/admin/controleurs/$serviceId/': typeof AdminControleursServiceIdIndexRoute
  '/admin/recharge/mobile/': typeof AdminRechargeMobileIndexRoute
  '/admin/controleurs/$serviceId/ticket/$ticketId/': typeof AdminControleursServiceIdTicketTicketIdIndexRoute
  '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/': typeof AdminControleursServiceIdTicketTicketIdMobileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/unauthorized'
    | '/admin/'
    | '/admin/comptes/$compteId'
    | '/admin/etudiants/$etudiantId'
    | '/admin/repreuneurs/$serviceId'
    | '/admin/restaurations/$restaurantId'
    | '/admin/services/$serviceId'
    | '/admin/agent-comptable/'
    | '/admin/caisse-principale/'
    | '/admin/comptes/'
    | '/admin/controleurs/'
    | '/admin/decades/'
    | '/admin/etudiants/'
    | '/admin/recharge/'
    | '/admin/recouvrement/'
    | '/admin/repreuneurs/'
    | '/admin/restaurations/'
    | '/admin/services/'
    | '/admin/sessions/'
    | '/admin/tickets/'
    | '/admin/controleurs/$serviceId/'
    | '/admin/recharge/mobile/'
    | '/admin/controleurs/$serviceId/ticket/$ticketId/'
    | '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/unauthorized'
    | '/admin'
    | '/admin/comptes/$compteId'
    | '/admin/etudiants/$etudiantId'
    | '/admin/repreuneurs/$serviceId'
    | '/admin/restaurations/$restaurantId'
    | '/admin/services/$serviceId'
    | '/admin/agent-comptable'
    | '/admin/caisse-principale'
    | '/admin/comptes'
    | '/admin/controleurs'
    | '/admin/decades'
    | '/admin/etudiants'
    | '/admin/recharge'
    | '/admin/recouvrement'
    | '/admin/repreuneurs'
    | '/admin/restaurations'
    | '/admin/services'
    | '/admin/sessions'
    | '/admin/tickets'
    | '/admin/controleurs/$serviceId'
    | '/admin/recharge/mobile'
    | '/admin/controleurs/$serviceId/ticket/$ticketId'
    | '/admin/controleurs/$serviceId/ticket/$ticketId/mobile'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/unauthorized'
    | '/admin/'
    | '/admin/comptes/$compteId'
    | '/admin/etudiants/$etudiantId'
    | '/admin/repreuneurs/$serviceId'
    | '/admin/restaurations/$restaurantId'
    | '/admin/services/$serviceId'
    | '/admin/agent-comptable/'
    | '/admin/caisse-principale/'
    | '/admin/comptes/'
    | '/admin/controleurs/'
    | '/admin/decades/'
    | '/admin/etudiants/'
    | '/admin/recharge/'
    | '/admin/recouvrement/'
    | '/admin/repreuneurs/'
    | '/admin/restaurations/'
    | '/admin/services/'
    | '/admin/sessions/'
    | '/admin/tickets/'
    | '/admin/controleurs/$serviceId/'
    | '/admin/recharge/mobile/'
    | '/admin/controleurs/$serviceId/ticket/$ticketId/'
    | '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/unauthorized': {
      id: '/admin/unauthorized'
      path: '/unauthorized'
      fullPath: '/admin/unauthorized'
      preLoaderRoute: typeof AdminUnauthorizedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets/': {
      id: '/admin/tickets/'
      path: '/tickets'
      fullPath: '/admin/tickets/'
      preLoaderRoute: typeof AdminTicketsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions/': {
      id: '/admin/sessions/'
      path: '/sessions'
      fullPath: '/admin/sessions/'
      preLoaderRoute: typeof AdminSessionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurations/': {
      id: '/admin/restaurations/'
      path: '/restaurations'
      fullPath: '/admin/restaurations/'
      preLoaderRoute: typeof AdminRestaurationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/repreuneurs/': {
      id: '/admin/repreuneurs/'
      path: '/repreuneurs'
      fullPath: '/admin/repreuneurs/'
      preLoaderRoute: typeof AdminRepreuneursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recouvrement/': {
      id: '/admin/recouvrement/'
      path: '/recouvrement'
      fullPath: '/admin/recouvrement/'
      preLoaderRoute: typeof AdminRecouvrementIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharge/': {
      id: '/admin/recharge/'
      path: '/recharge'
      fullPath: '/admin/recharge/'
      preLoaderRoute: typeof AdminRechargeIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etudiants/': {
      id: '/admin/etudiants/'
      path: '/etudiants'
      fullPath: '/admin/etudiants/'
      preLoaderRoute: typeof AdminEtudiantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/decades/': {
      id: '/admin/decades/'
      path: '/decades'
      fullPath: '/admin/decades/'
      preLoaderRoute: typeof AdminDecadesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/controleurs/': {
      id: '/admin/controleurs/'
      path: '/controleurs'
      fullPath: '/admin/controleurs/'
      preLoaderRoute: typeof AdminControleursIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comptes/': {
      id: '/admin/comptes/'
      path: '/comptes'
      fullPath: '/admin/comptes/'
      preLoaderRoute: typeof AdminComptesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caisse-principale/': {
      id: '/admin/caisse-principale/'
      path: '/caisse-principale'
      fullPath: '/admin/caisse-principale/'
      preLoaderRoute: typeof AdminCaissePrincipaleIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agent-comptable/': {
      id: '/admin/agent-comptable/'
      path: '/agent-comptable'
      fullPath: '/admin/agent-comptable/'
      preLoaderRoute: typeof AdminAgentComptableIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services/$serviceId': {
      id: '/admin/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/admin/services/$serviceId'
      preLoaderRoute: typeof AdminServicesServiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/restaurations/$restaurantId': {
      id: '/admin/restaurations/$restaurantId'
      path: '/restaurations/$restaurantId'
      fullPath: '/admin/restaurations/$restaurantId'
      preLoaderRoute: typeof AdminRestaurationsRestaurantIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/repreuneurs/$serviceId': {
      id: '/admin/repreuneurs/$serviceId'
      path: '/repreuneurs/$serviceId'
      fullPath: '/admin/repreuneurs/$serviceId'
      preLoaderRoute: typeof AdminRepreuneursServiceIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/etudiants/$etudiantId': {
      id: '/admin/etudiants/$etudiantId'
      path: '/etudiants/$etudiantId'
      fullPath: '/admin/etudiants/$etudiantId'
      preLoaderRoute: typeof AdminEtudiantsEtudiantIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comptes/$compteId': {
      id: '/admin/comptes/$compteId'
      path: '/comptes/$compteId'
      fullPath: '/admin/comptes/$compteId'
      preLoaderRoute: typeof AdminComptesCompteIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recharge/mobile/': {
      id: '/admin/recharge/mobile/'
      path: '/recharge/mobile'
      fullPath: '/admin/recharge/mobile/'
      preLoaderRoute: typeof AdminRechargeMobileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/controleurs/$serviceId/': {
      id: '/admin/controleurs/$serviceId/'
      path: '/controleurs/$serviceId'
      fullPath: '/admin/controleurs/$serviceId/'
      preLoaderRoute: typeof AdminControleursServiceIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/controleurs/$serviceId/ticket/$ticketId/': {
      id: '/admin/controleurs/$serviceId/ticket/$ticketId/'
      path: '/controleurs/$serviceId/ticket/$ticketId'
      fullPath: '/admin/controleurs/$serviceId/ticket/$ticketId/'
      preLoaderRoute: typeof AdminControleursServiceIdTicketTicketIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/': {
      id: '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/'
      path: '/controleurs/$serviceId/ticket/$ticketId/mobile'
      fullPath: '/admin/controleurs/$serviceId/ticket/$ticketId/mobile/'
      preLoaderRoute: typeof AdminControleursServiceIdTicketTicketIdMobileIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminUnauthorizedRoute: typeof AdminUnauthorizedRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminComptesCompteIdRoute: typeof AdminComptesCompteIdRoute
  AdminEtudiantsEtudiantIdRoute: typeof AdminEtudiantsEtudiantIdRoute
  AdminRepreuneursServiceIdRoute: typeof AdminRepreuneursServiceIdRoute
  AdminRestaurationsRestaurantIdRoute: typeof AdminRestaurationsRestaurantIdRoute
  AdminServicesServiceIdRoute: typeof AdminServicesServiceIdRoute
  AdminAgentComptableIndexRoute: typeof AdminAgentComptableIndexRoute
  AdminCaissePrincipaleIndexRoute: typeof AdminCaissePrincipaleIndexRoute
  AdminComptesIndexRoute: typeof AdminComptesIndexRoute
  AdminControleursIndexRoute: typeof AdminControleursIndexRoute
  AdminDecadesIndexRoute: typeof AdminDecadesIndexRoute
  AdminEtudiantsIndexRoute: typeof AdminEtudiantsIndexRoute
  AdminRechargeIndexRoute: typeof AdminRechargeIndexRoute
  AdminRecouvrementIndexRoute: typeof AdminRecouvrementIndexRoute
  AdminRepreuneursIndexRoute: typeof AdminRepreuneursIndexRoute
  AdminRestaurationsIndexRoute: typeof AdminRestaurationsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminSessionsIndexRoute: typeof AdminSessionsIndexRoute
  AdminTicketsIndexRoute: typeof AdminTicketsIndexRoute
  AdminControleursServiceIdIndexRoute: typeof AdminControleursServiceIdIndexRoute
  AdminRechargeMobileIndexRoute: typeof AdminRechargeMobileIndexRoute
  AdminControleursServiceIdTicketTicketIdIndexRoute: typeof AdminControleursServiceIdTicketTicketIdIndexRoute
  AdminControleursServiceIdTicketTicketIdMobileIndexRoute: typeof AdminControleursServiceIdTicketTicketIdMobileIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUnauthorizedRoute: AdminUnauthorizedRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminComptesCompteIdRoute: AdminComptesCompteIdRoute,
  AdminEtudiantsEtudiantIdRoute: AdminEtudiantsEtudiantIdRoute,
  AdminRepreuneursServiceIdRoute: AdminRepreuneursServiceIdRoute,
  AdminRestaurationsRestaurantIdRoute: AdminRestaurationsRestaurantIdRoute,
  AdminServicesServiceIdRoute: AdminServicesServiceIdRoute,
  AdminAgentComptableIndexRoute: AdminAgentComptableIndexRoute,
  AdminCaissePrincipaleIndexRoute: AdminCaissePrincipaleIndexRoute,
  AdminComptesIndexRoute: AdminComptesIndexRoute,
  AdminControleursIndexRoute: AdminControleursIndexRoute,
  AdminDecadesIndexRoute: AdminDecadesIndexRoute,
  AdminEtudiantsIndexRoute: AdminEtudiantsIndexRoute,
  AdminRechargeIndexRoute: AdminRechargeIndexRoute,
  AdminRecouvrementIndexRoute: AdminRecouvrementIndexRoute,
  AdminRepreuneursIndexRoute: AdminRepreuneursIndexRoute,
  AdminRestaurationsIndexRoute: AdminRestaurationsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminSessionsIndexRoute: AdminSessionsIndexRoute,
  AdminTicketsIndexRoute: AdminTicketsIndexRoute,
  AdminControleursServiceIdIndexRoute: AdminControleursServiceIdIndexRoute,
  AdminRechargeMobileIndexRoute: AdminRechargeMobileIndexRoute,
  AdminControleursServiceIdTicketTicketIdIndexRoute:
    AdminControleursServiceIdTicketTicketIdIndexRoute,
  AdminControleursServiceIdTicketTicketIdMobileIndexRoute:
    AdminControleursServiceIdTicketTicketIdMobileIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
